# Introduction to Vectors and Matrices

In [1]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

# Basics of NumPy Array Object

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print("We just create a ", type(x))

We just create a  <class 'numpy.ndarray'>


In [4]:
print("Our template has shape as" ,x.shape)

Our template has shape as (2, 3)


In [5]:
print("Total size is",x.size)

Total size is 6


In [6]:
print("The dimension of our array is " ,x.ndim)

The dimension of our array is  2


In [7]:
print("Data type of elements are",x.dtype)

Data type of elements are int32


In [8]:
print("It consumes",x.nbytes,"bytes")

It consumes 24 bytes


In [10]:
x = np.array([[1,2,3],[4,5,6]], dtype = float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
48


In [11]:
x = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [12]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[         1          2          3]
 [         4 4294967291          6]]
24


C:\Users\CursosTardes\AppData\Local\Temp\ipykernel_14120\530792209.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -5 to uint32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)


In [13]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 comsues",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 comsues",x.nbytes, "bytes")

int64 comsues 48 bytes
int32 comsues 24 bytes


In [15]:
x_copy = np.array(x, dtype = float)
x_copy 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
Data_Cancer = np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(Data_Cancer_New.nbytes)

<class 'numpy.ndarray'>
float64
80000000
40000000


# NumPy Array Operations

In [20]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [21]:
my_array +2

array([ 4, 16,  8, 10])

In [22]:
my_array -1

array([ 1, 13,  5,  7])

In [23]:
my_array *2

array([ 4, 28, 12, 16])

In [24]:
my_array /2

array([1., 7., 3., 4.])

In [25]:
second_array = np.zeros(4) + 3
second_array 

array([3., 3., 3., 3.])

In [26]:
my_array - second_array 

array([-1., 11.,  3.,  5.])

In [27]:
second_array / my_array 

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [28]:
second_array = np.ones(4)+3
second_array

array([4., 4., 4., 4.])

In [29]:
my_array - second_array 

array([-2., 10.,  2.,  4.])

In [30]:
second_array / my_array 

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [31]:
second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
second_array = np.identity(4)+3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [33]:
my_array - second_array 

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [34]:
second_array / my_array 

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [35]:
x = np.arange(3,7,0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [36]:
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [37]:
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

In [38]:
np.logspace(3, 4, num=5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [39]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [40]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

array([ True, False, False,  True])

In [41]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

False

In [42]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

array([False,  True,  True, False])

In [43]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

array([ True,  True, False,  True])

In [44]:
np.logical_and(x,y)

array([False,  True, False, False])

In [45]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [46]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [47]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [48]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [52]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [54]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.sum(x)

36

In [56]:
np.amin(x)

0

In [57]:
np.amax(x)

8

In [58]:
np.amin(x, axis=0)

array([0, 1, 2])

In [59]:
np.amin(x, axis=1)

array([0, 3, 6])

In [60]:
np.percentile(x, 80)

6.4

In [61]:
x = np.array([1,-21,3,-3])
np.argmax(x)

2

In [62]:
np.argmin(x)

1

In [63]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [64]:
np.mean(x)

7.666666666666667

In [65]:
np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [66]:
np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [67]:
np.median(x)

4.5

In [68]:
np.std(x)

6.394442031083626

# Working with Multidimensional Arrays

In [69]:
c = np.ones((4, 4))
c*c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [71]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [72]:
y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y,x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [73]:
from scipy import stats
x= np.random.rand(100,10)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

array([[ 5.01345264e-01,  8.17656286e-02, -1.89726583e-02,
        -1.13708305e+00,  6.65843338e-03,  9.87780898e-01],
       [ 5.09781404e-01,  8.27278671e-02, -8.91464583e-02,
        -1.15337637e+00,  5.56389626e-03,  9.99886766e-01],
       [ 5.30114892e-01,  8.76572289e-02, -1.16134053e-01,
        -1.14360226e+00,  2.16478014e-03,  9.92655568e-01],
       [ 4.91922799e-01,  8.08501137e-02,  1.17110875e-01,
        -1.25900101e+00,  3.37112409e-02,  9.93593723e-01],
       [ 4.88199725e-01,  8.43896864e-02,  6.00696239e-02,
        -1.02743107e+00,  1.11520126e-03,  9.89738809e-01],
       [ 5.19559278e-01,  7.43980222e-02,  5.13654107e-02,
        -1.11940552e+00,  8.43881158e-03,  9.93836388e-01],
       [ 5.13398487e-01,  7.07947963e-02, -8.34297618e-02,
        -1.16505360e+00,  2.80687206e-02,  9.67208168e-01],
       [ 4.77109995e-01,  8.74075660e-02,  4.33936392e-02,
        -1.31788452e+00,  1.41998185e-02,  9.89754485e-01],
       [ 4.81532714e-01,  8.77403772e-02,  2.930

In [74]:
import numpy.ma as ma
x = np.arange(6)
print(x.mean())
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

2.5


3.0

In [75]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [76]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

# Indexing, Slicing, Reshaping, Resizing, Broadcasting

In [77]:
x = ["USA","France", "Germany","England"]
x[2]

'Germany'

In [78]:
x = ('USA',3,"France",4)
x[2]

'France'

In [79]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x[5]

5

In [81]:
x[-2]

8

In [82]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [83]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x[2:8:2]

array([2, 4, 6])

In [85]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [88]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [89]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
x[[0,1,2],[0,1,3]]

array([ 0,  5, 11])

In [91]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.resize(x,(2,2))

array([[0, 1],
       [2, 3]])

In [93]:
np.resize(x,(6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [94]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [95]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [96]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [97]:
y = np.arange(2).reshape(1,2)
y

array([[0, 1]])

In [98]:
x*y

array([[0, 1],
       [0, 3]])

#### Operaciones con arrays y difusión

NumPy admite operaciones elemento por elemento (element-wise), que aplican una función a cada elemento del array. Entre estas operaciones se incluyen la suma, resta, multiplicación, división, etc. Para las operaciones elemento por elemento, los arrays de entrada deben tener la misma forma o ser transmitidos a la misma forma.

In [1]:
import numpy as np

a = np.array([6, 5, 4])
b = np.array([3, 2, 1])

print('a + b:', a + b)
print('a * b:', a * b)

a + b: [9 7 5]
a * b: [18 10  4]


NumPy ofrece varias funciones de agregación que permiten calcular estadísticas resumidas sobre los elementos de un array.

In [2]:
arr = np.array([[33, 5, 4], [3, 2, 10]]) 

 # suma todos elementos
print('Sum: ', np.sum(arr))

# valor medio de los elementos
print('Mean: ', np.mean(arr))

# standard deviation
print('Standard deviation: ', np.std(arr))

Sum:  57
Mean:  9.5
Standard deviation:  10.812801055539063


La difusión es una función poderosa en NumPy que permite realizar operaciones en arrays de diferentes formas. Esto se logra mediante la expansión automática de uno o ambos arrays a la forma del otro array de acuerdo con un conjunto de reglas de difusión.

In [4]:
# ejemplo de difusion
a = np.array([3, 2, 1])
b = 4

# multiplicar cada elemento de 'a' por scalar 'b'
print('a * b : ', a * b)


a * b :  [12  8  4]


#### Reglas de difusión:

- Si los arrays tienen una cantidad diferente de dimensiones, la forma del array más pequeño se complementa con unidades a la izquierda.
  
- Si la forma de los arrays no coincide en alguna dimensión, el array con forma igual a 1 en esa dimensión se extiende para coincidir con la otra forma.
  
- Si en alguna dimensión los tamaños no coinciden y ninguno de ellos es igual a 1, se produce un error.

#### Operaciones matriciales y álgebra lineal

NumPy permite realizar una amplia gama de operaciones matriciales, como suma, resta y multiplicación. Para estas operaciones, las matrices de entrada deben tener formas compatibles.

In [3]:
A = np.array([[4, 3], [2, 1]])
B = np.array([[8, 7], [6, 5]])

# sumar matrix
C = A + B
print("A + B:\n", C)

# restar matrix
D = A - B
print("A - B:\n", D)


A + B:
 [[12 10]
 [ 8  6]]
A - B:
 [[-4 -4]
 [-4 -4]]


In [4]:
E = A * B
print("Element-wise multiplication:\n", E)

F = np.dot(A, B)
print("Matrix multiplication (dot product):\n",F)

Element-wise multiplication:
 [[32 21]
 [12  5]]
Matrix multiplication (dot product):
 [[50 43]
 [22 19]]


La transposición de una matriz se obtiene al intercambiar sus filas y columnas. La matriz inversa de una matriz cuadrada es aquella que, al multiplicarse por la matriz original, da como resultado la matriz identidad.

In [5]:
import numpy as np
G = np.transpose(A)
print("Transpose of A:\n", G)

H = np.linalg.inv(A)
print("Inverse of A:\n", H)

Transpose of A:
 [[4 2]
 [3 1]]
Inverse of A:
 [[-0.5  1.5]
 [ 1.  -2. ]]


In [6]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)


Determinant of A: -2.0


In [7]:
eig_vals, eig_vecs = np.linalg.eig(A)
print("Eigenvalues of A:", eig_vals)
print("Eigenvectors of A:\n", eig_vecs)

Eigenvalues of A: [ 5.37228132 -0.37228132]
Eigenvectors of A:
 [[ 0.90937671 -0.56576746]
 [ 0.41597356  0.82456484]]


In [8]:
x = np.linalg.solve(A, np.array([1, 1]))
print("Solution of Ax = [1, 1]:", x)

Solution of Ax = [1, 1]: [ 1. -1.]
